apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "admission.fullname" . }}
  labels:
  {{ include "admission.labels" . | indent 4 }}
webhooks:
  - name: "mutate.appconfig.core.oam.dev"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: ["core.oam.dev"]
        apiVersions: ["v1alpha1"]
        resources: ["applicationconfigurations"]
        scope: "Namespaced"
    clientConfig:
      service:
        namespace: {{.Release.Namespace}}
        name: {{ template "admission.fullname" . }}
        path: /mutating-appconfig
      caBundle: "{{.Values.caBundle}}"
    admissionReviewVersions: ["v1beta1"]
    timeoutSeconds: 5
---

apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ template "admission.fullname" . }}
  labels:
{{ include "admission.labels" . | indent 4 }}
webhooks:
  - name: "validate.appconfig.core.oam.dev"
    rules:
      - apiGroups:   ["core.oam.dev"]
        apiVersions: ["v1alpha1"]
        operations:  ["CREATE","UPDATE"]
        resources:   ["applicationconfigurations"]
        scope:       "Namespaced"
    clientConfig:
      service:
        namespace: {{.Release.Namespace}}
        name: {{ template "admission.fullname" . }}
        path: /appconfig
      caBundle: "{{.Values.caBundle}}"
    admissionReviewVersions: ["v1beta1"]
    timeoutSeconds: 5
  - name: "validate.component.core.oam.dev"
      rules:
        - apiGroups:   ["core.oam.dev"]
          apiVersions: ["v1alpha1"]
          operations:  ["CREATE","UPDATE"]
          resources:   ["components"]
          scope:       "Namespaced"
      clientConfig:
        service:
          namespace: {{.Release.Namespace}}
          name: {{ template "admission.fullname" . }}
          path: /component
        caBundle: "{{.Values.caBundle}}"
      admissionReviewVersions: ["v1beta1"]
      timeoutSeconds: 5
  - name: "validate.scope.core.oam.dev"
      rules:
        - apiGroups:   ["core.oam.dev"]
          apiVersions: ["v1alpha1"]
          operations:  ["CREATE","UPDATE"]
          resources:   ["scopes"]
          scope:       "Namespaced"
      clientConfig:
        service:
          namespace: {{.Release.Namespace}}
          name: {{ template "admission.fullname" . }}
          path: /scope
        caBundle: "{{.Values.caBundle}}"
      admissionReviewVersions: ["v1beta1"]
      timeoutSeconds: 5
  - name: "validate.trait.core.oam.dev"
      rules:
        - apiGroups:   ["core.oam.dev"]
          apiVersions: ["v1alpha1"]
          operations:  ["CREATE","UPDATE"]
          resources:   ["traits"]
          scope:       "Namespaced"
      clientConfig:
        service:
          namespace: {{.Release.Namespace}}
          name: {{ template "admission.fullname" . }}
          path: /traits
        caBundle: "{{.Values.caBundle}}"
      admissionReviewVersions: ["v1beta1"]
      timeoutSeconds: 5
